server:
  port: 8083

spring:
  application:
    name: sa-token-demo-interceptor

# Sa-Token 配置
sa-token:
  # token 名称 (同时也是 cookie 名称)
  token-name: satoken
  # token 有效期 (单位: 秒) -1 表示永久有效
  timeout: 2592000
  # token 临时有效期 (指定时间内无操作就视为 token 过期) (单位: 秒)
  activity-timeout: 1800
  # 是否允许同一账号并发登录 (为 true 时允许一起登录, 为 false 时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token (为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token)
  is-share: false
  # token 风格 (默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik)
  token-style: uuid
  # 是否输出操作日志
  is-log: true

logging:
  level:
    root: INFO
    com.it666: DEBUG
